openapi: 3.0.3
info:
  title: DataScientest Agent de Tourisme API
  version: v1
servers:
- url: https://be05-37-171-207-106.ngrok-free.app/
paths:
  /:
    get:
      description: Get Restaurants, Hotels or Point of Interests from DATAtourisme data base.
      parameters:
      - name: query_element
        description: Desired object's type.
        example: Hotel
        in: query
        schema:
          type: string
          enum: ['Restaurant', 'Hotel', 'PointOfInterest']
      - name: nom
        description: Enter your name.
        example: John Doe
        in: query
        schema:
          type: string
      - name: ma_lat
        description: Personal GPS geolocation latitude.
        example: 48.75
        in: query
        schema:
          type: number
          minimum: -90.0
          maximum: 90.0
      - name: ma_lon
        description: Personal GPS geolocation longitude.
        example: -102.54
        in: query
        schema:
          type: number
          minimum: -180.0
          maximum: 180.0
      - name: file
        description: If set to true, returns a json file as an attachment. Any other value will not return a json file.
        example: true
        in: query
        schema:
          type: string
          enum: ['true', 'false']
          default: 'false'
      - name: ngrok-skip-browser-warning
        description: Skips ngrok warning page.
        in: header
        schema:
          type: string
          default: value
      responses:
        '200':
          description: A bunch of restaurants, hotels or point of interests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  infos_utilisateur:
                    type: object
                    description: Gathers user's personal information and metadata.
                    properties:
                      nom:
                        type: string
                        description: user's name.
                        example: John Doe
                      ma_lat:
                        type: number
                        minimum: -90.0
                        maximum: 90.0
                        description: Personal GPS geolocation latitude.
                        example: 48.75
                      ma_lon:
                        type: number
                        minimum: -180.0
                        maximum: 180.0
                        description: Personal GPS geolocation longitude.
                        example: -102.54
                      ip_address:
                        type: string
                        description: User's device IP address.
                        example: 37.171.217.106
                      hostname:
                        type: string
                        description: User's device hostname
                        example: Tecra-7580
                  objects:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the object returned from the DATAtourisme database.
                          example: HÔTEL DU DOMAINE DE SOMMEDIEUE
                        lat:
                          type: number
                          minimum: -90.0
                          maximum: 90.0
                          description: Object's latitude.
                          example: 49.088441929231
                        lon:
                          type: number
                          minimum: -180.0
                          maximum: 180.0
                          description: Object's longitude.
                          example: 5.46923031509709
        '404':
          description: Page does not exist.